### PR TITLE
Adds update token endpoint

### PR DESCRIPTION
**Pull request by kritzcreek**

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me, shame there's no documentation on this endpoint existing though so I have no idea whether it's implemented correctly or not :wink:

**Comment by kritzcreek** [comment]
See https://github.com/slamdata/slamdata-backend/pull/314/files

**Comment by garyb** [comment]
Oh I see, I was checking the current README.

**Comment by kritzcreek** [comment]
Yeah, I had the same problem initially ^^

**Comment by beckyconning** [comment]
> Looks good to me, shame there's no documentation on this endpoint existing though so I have no idea whether it's implemented correctly or not 😉

https://slamdata.slack.com/archives/C09MRGSHW/p1519377041000246

@nicflores

**Comment by garyb** [comment]
@beckyconning it's done, I just missed it as it's in a PR still

**Review by garyb — APPROVED** [review]

**Comment by nicflores** [comment]
@beckyconning, sorry about that. I submitted a PR yesterday against SB with
some documentation.

**Pull request merged**
