### PR TITLE
Change GroupPaths from files to directories

### PR DESCRIPTION
**Pull request by kritzcreek**
Still need to make the corresponding changes in slamdata

### CODE REVIEW

**Comment by kritzcreek** [comment]
This is ready to go now. The code will need to be changed again after https://github.com/slamdata/quasar-advanced/issues/192 is done, but at least that change will be very isolated now.

**Comment by kritzcreek** [comment]
```
Starting Quasar...
Error: An error occurred: Error: Unable to access jarfile ../../../jars/quasar.jar
    at Object.exports.error (/home/travis/build/slamdata/purescript-quasar/output/Control.Monad.Eff.Exception/foreign.js:8:10)
    at /home/travis/build/slamdata/purescript-quasar/output/Test.Util.Process/index.js:59:199
    at /home/travis/build/slamdata/purescript-quasar/output/Control.Monad.Eff/foreign.js:12:14
    at /home/travis/build/slamdata/purescript-quasar/output/Control.Monad.Eff/foreign.js:12:20
    at Socket.<anonymous> (/home/travis/build/slamdata/purescript-quasar/output/Node.Stream/foreign.js:35:29)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
* ERROR: Subcommand terminated with exit code 1
```

Does not seem like it's about my PR. What's broken here? Is the problem a change in naming scheme for quasar releases?

**Review by beckyconning — APPROVED** [review]

**Comment by beckyconning** [comment]
I agree this failure doesn't seem to be relevant to this PR.

https://github.com/quasar-analytics/quasar/releases it doesn't look like the naming changed though?

**Comment by garyb** [comment]
It's revoked-auth-token related, I just updated it so it's working again now :tada:

**Pull request merged**
