### PR TITLE
SD 2068 - add header config to CSV toMediaType

### PR DESCRIPTION
**Pull request by Cmdv**
this fixes https://github.com/slamdata/slamdata/issues/2068

### CODE REVIEW

**Review by garyb — CHANGES_REQUESTED** [review]
This isn't right, the thing that needs fixing is the escaping of the delimiter/chars. The disposition/zip encoding is added to the `MediaType` later, in the code in SlamData.

**Comment by Cmdv** [comment]
Ah ok, I just changed it to match bellow which was in last comment [here](https://github.com/slamdata/slamdata/issues/2068#issuecomment-321157911):

```
application/zip,text/csv;columnDelimiter=",";rowDelimiter="\n";quoteChar="";escapeChar="";disposition="attachment;filename*=UTF-8''mytest.zip"
```
but did feel weird to leave some values as empty string!! should of put WIP as not tested it yet 😄

**Review by garyb — CHANGES_REQUESTED** [review]
Sorry, I don't think that's gonna do it either. It means it'll only work with the default values - we need to escape them when it is rendered as a `MediaType`.

**Comment by Cmdv** [comment]
@garyb ah ok, do you mean something like this:

` "columnDelimiter=\"" <> opts.columnDelimiter <> "\""`

**Comment by Cmdv** [comment]
@garyb ready for review 😄

**Review by garyb — APPROVED** [review]

**Pull request merged**
