### PR TITLE
Case insensitive header names and header rather than index

### PR DESCRIPTION
**Pull request by beckyconning**

### CODE REVIEW

**Comment by beckyconning** [comment]
@cryogenian please review if you're still up for it : )

**Comment by garyb** [comment]
You could have just used `find` here I think? But no matter :smile:

**Comment by beckyconning** [comment]
I couldn't find `find`! #find

**Comment by garyb** [comment]
https://pursuit.purescript.org/search?q=find? 😜  (it's in `foldable-traversable` - but re-exported from arrays/lists in the new releases)

**Pull request merged**
